drive/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('upload/', views.drive_upload, name='drive_upload'),
    url('round/details/', views.drive_upload, name='round_details'),
    url('student/attendance/', views.student_attendence, name='student_attendance'),
    url('student/list/', views.student_list, name='student_list'),
    url('volunteer/search', views.volunteer_search, name='volunteer_search'),
    url('volunteer/update/', views.volunteer_update, name='volunteer_update'),
    url('company/search', views.company_search, name="company_search"),
    url('placed/details', views.placed_details, name="placed_details"),
    url('placed/analysis', views.placed_analysis, name='placed_analysis'),
    url('college/analysis', views.college_analysis, name='college_analysis'),
    url('total/analysis', views.total_analysis, name='total_analysis'),
    url('company/analysis', views.company_analysis, name='company_analysis'),
    url('report/pdf',views.report_pdf,name='report_pdf'),
]

tnp_is/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls')),
    path('drive/',include('drive.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('all/report', TemplateView.as_view(template_name='all_report.html'), name='all_report')# new
]

drive/models.py
from djongo import models


class Drive_Rounds(models.Model):
    round_name = models.CharField(max_length=20, blank=False)
    round_number = models.CharField(max_length=2, blank=False)

    class Meta:
        abstract = True


class Eligibility(models.Model):
    tenth_marks = models.DecimalField(max_digits=5, decimal_places=3)
    diploma_12 = models.DecimalField(max_digits=5, decimal_places=3)
    engineering = models.DecimalField(max_digits=5, decimal_places=3)

    class Meta:
        abstract = True


class Attendance(models.Model):
    _id = models.CharField(max_length=10, null=False, blank=False, primary_key=True, unique=True)
    name = models.CharField(max_length=80, null=False, blank=False)
    branch = models.CharField(max_length=50, null=False, blank=False)

    class Meta:
        abstract = True


class Drive(models.Model):
    Campus_choice = (('On', 'On'), ('Off', 'Off'), ('Pool', 'Pool'))

    _id = models.CharField(max_length=60, null=False, blank=False, primary_key=True, unique=True)
    company_name = models.CharField(max_length=50, null=False, blank=False)
    date = models.CharField(max_length=10, null=False, blank=False)
    time = models.CharField(max_length=15, null=False, blank=False)
    venue = models.CharField(max_length=100, blank=False, null=False)
    campus_type = models.CharField(max_length=10, choices=Campus_choice, default='On', null=False, blank=False)
    Computer = models.BooleanField(default=False)
    Civil = models.BooleanField(default=False)
    Mechanical = models.BooleanField(default=False)
    IT = models.BooleanField(default=False)
    Instrumentation = models.BooleanField(default=False)
    Production = models.BooleanField(default=False)
    ENTC = models.BooleanField(default=False)
    base_package = models.DecimalField(max_digits=8, decimal_places=3, blank=False, null=False)
    login_key = models.CharField(max_length=15, null=False, blank=False)
    rounds = models.ArrayModelField(model_container=Drive_Rounds)
    eligibility = models.ArrayModelField(model_container=Eligibility)
    eligible_student = models.ArrayModelField(model_container=Attendance)
    round1_student = models.ArrayModelField(model_container=Attendance)
    round2_student = models.ArrayModelField(model_container=Attendance)
    round3_student = models.ArrayModelField(model_container=Attendance)
    round4_student = models.ArrayModelField(model_container=Attendance)
    round5_student = models.ArrayModelField(model_container=Attendance)
    round6_student = models.ArrayModelField(model_container=Attendance)
    round7_student = models.ArrayModelField(model_container=Attendance)
    round8_student = models.ArrayModelField(model_container=Attendance)
    placed_student = models.ArrayModelField(model_container=Attendance)

drive/views.py
import os
import random
import string
from datetime import date
from io import BytesIO

import matplotlib.pyplot as plt
import numpy as np
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from pymongo import MongoClient
from xhtml2pdf import pisa


# Drive Upload
@login_required
def drive_upload(request):
    if request.method == 'POST':
        try:
            con = MongoClient()
            db = con["tnp_management"]
            collection_candidate = db["registration_candidate"]
            collection = db["drive_drive"]

            # ---------Branch--------------
            branch_ls = []
            computer = request.POST.get("Computer")
            if computer == None:
                computer = False
            else:
                computer = True
                branch_ls.append("computer")

            IT = request.POST.get("IT")
            if IT == None:
                IT = False
            else:
                IT = True
                branch_ls.append("information technology")

            CIVIL = request.POST.get("CIVIL")
            if CIVIL == None:
                CIVIL = False
            else:
                CIVIL = True
                branch_ls.append("civil")

            MECH = request.POST.get("MECH")
            if MECH == None:
                MECH = False
            else:
                MECH = True
                branch_ls.append("mechanical")

            INSTRU = request.POST.get("INSTRU")
            if INSTRU == None:
                INSTRU = False
            else:
                INSTRU = True
                branch_ls.append("instrumentation")

            PROD = request.POST.get("PROD")
            if PROD == None:
                PROD = False
            else:
                PROD = True
                branch_ls.append("production")

            ENTC = request.POST.get("ENTC")
            if ENTC == None:
                ENTC = False
            else:
                ENTC = True
                branch_ls.append("entc")

            date_ls = str(request.POST.get("drive_date")).split("-")
            drive_id = str(request.POST.get("name")).lower() + str(date_ls[0])
            login_key = randomStringDigits()

            round_ls = str(request.POST.get("other")).split(',')
            round_dict = []
            if request.POST.get("round1"):
                round_dict.append({
                    "round_name": request.POST.get("round1"),
                    "round_number": "1"
                })
                if request.POST.get("round2"):
                    round_dict.append({
                        "round_name": request.POST.get("round2"),
                        "round_number": "2"
                    })
                    if request.POST.get("round3"):
                        round_dict.append({
                            "round_name": request.POST.get("round3"),
                            "round_number": "3"
                        })

                        j = 3
                        for i in round_ls:
                            if i:
                                j = j + 1
                                round_dict.append({"round_name": i, "round_number": str(j)})

            eligible_student = []
            print(branch_ls)
            query = {
                "tenth": {"$gte": request.POST.get('tenth')},
                "diploma_12": {"$gte": request.POST.get("diploma_12")},
                "engineering": {"$gte": request.POST.get("engineering")},
                "branch": {"$in": branch_ls},
            }

            student_details = collection_candidate.find(query)
            for i in student_details:
                print(i)
                id = i["_id"]
                name = i["name"]
                branch = i["branch"]
                eligible = int(i["eligible"]) + 1
                collection_candidate.update({"_id": id}, {"$set": {"eligible": eligible}})
                student_temp = {"_id": id, "name": name, "branch": branch}
                eligible_student.append(student_temp)

            drive_dic = {
                '_id': drive_id,
                'company_name': str(request.POST.get("name")).lower(),
                'date': request.POST.get("drive_date"),
                'venue': request.POST.get("place"),
                'time': request.POST.get("drive_time"),
                'rounds': round_dict,
                'login_key': login_key,
                'Computer': computer,
                'Civil': CIVIL,
                'Mechanical': MECH,
                'IT': IT,
                'Instrumentation': INSTRU,
                'Production': PROD,
                'ENTC': ENTC,
                'eligibility': [{
                    'tenth_marks': request.POST.get("tenth"),
                    'diploma_12': request.POST.get("diploma_12"),
                    'engineering': request.POST.get("engineering"),
                }],
                'base_package': request.POST.get("package"),
                'campus_type': request.POST.get("campus"),
                'eligible_student': eligible_student,
                "round1_student": [],
                "round2_student": [],
                "round3_student": [],
                "round4_student": [],
                "round5_student": [],
                "round6_student": [],
                "round7_student": [],
                "round8_student": [],
                "placed_student": [],
            }
            rec = collection.insert_one(drive_dic)
            print(rec)
            return render(request, 'drive/round_details.html', {'login_key': login_key, })
        except Exception as e:
            print(e)
            return render(request, 'drive/drive_upload.html', {"error": "Drive_id number is already registered"})
    else:
        return render(request, 'drive/drive_upload.html', {})


def randomStringDigits(stringLength=8):
    """Generate a random string of letters and digits """
    lettersAndDigits = string.ascii_letters + string.digits
    return ''.join(random.choice(lettersAndDigits) for i in range(stringLength))


companyname = []


def student_attendence(request):
    if request.method == 'POST':
        try:
            con = MongoClient()
            db = con["tnp_management"]
            collection_candidate = db["registration_candidate"]
            collection_drive = db["drive_drive"]

            query_student = {"_id": request.POST.get('pnr'), }

            student_information = collection_candidate.find(query_student)

            query = {
                "date": str(date.today()),
                "eligible_student._id": request.POST.get('pnr'),
            }

            eligible_companies = collection_drive.find(query)

            id = request.POST.get('pnr')
            name = None
            branch = None

            for i in student_information:
                name = i["name"]
                branch = i["branch"]

            companyname.clear()
            companies = []

            for i in eligible_companies:
                print(i)
                companyname.append(i["company_name"])
                cmp = dict(cname=i["company_name"], time=i["time"], location=i["venue"])
                companies.append(cmp)

            print("comapny", companyname)
            return render(request, 'drive/student_list.html',
                          {"id": id, 'name': name, 'branch': branch, 'companies': companies})
        except Exception as e:
            print(e)
            return render(request, 'drive/student_attendance.html', {"error": 'Some error occured'})

    else:
        return render(request, 'drive/student_attendance.html', {})


def student_list(request):
    if request.method == 'POST':
        try:
            con = MongoClient()
            db = con["tnp_management"]
            collection_drive = db["drive_drive"]
            collection_candidate = db["registration_candidate"]

        except Exception as e:
            print({"exception": e})  # Console log
            return render(request, 'drive/student_list.html', {"error": "Connection Failed"})

        try:
            print("Connection established")

            date_ls = str(date.today()).split("-")
            year = str(date_ls[0])
            j = 0

            print(companyname)
            for i in companyname:
                print(i, request.POST.get(str(i)))
                if request.POST.get(str(i)) == 'Yes':
                    rec = collection_drive.find(
                        {"$and": [{"_id": str(i) + year}, {"round1_student._id": request.POST.get('id')}]})
                    flag = True

                    for i in rec:
                        flag = False
                        break

                    if flag:

                        collection_drive.update({"_id": str(i) + year}, {"$push": {"round1_student": {
                            '_id': request.POST.get('id'),
                            'name': request.POST.get('name'),
                            'branch': request.POST.get('branch'), }}
                        })
                        j = j + 1
                        student_records = collection_candidate.find({"_id": request.POST.get('id')})
                        for i in student_records:
                            print(i)
                            id = i["_id"]
                            round1 = int(i["round1"]) + j
                            collection_candidate.update({"_id": id}, {"$set": {"round1": round1}})

                        return HttpResponse("Congratulations.....You are in!!")
                    else:
                        return HttpResponse("You are already added to list")
        except Exception as e:
            print({"exception": e})

templates/drive/college_graph.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'drive/graphs/result_college.png' %}" rel="stylesheet" type="image/png">
</head>
<body>

    {% block content %}
    <h1 align="center">
        {{ college_name }}
    </h1>
    <p align="center"><img src="{% static 'drive/graphs/result_college.png' %}"></p>
    <br>

{% endblock %}
</body>

templates/drive/company_graph.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'drive/graphs/result_company_analysis.png' %}" rel="stylesheet" type="image/png">
</head>
<body>

    {% block content %}
    <h1 align="center">
        {{ college_name }}
    </h1>
    <p align="center"><img src="{% static 'drive/graphs/result_company_analysis.png' %}"></p>
    <br>

{% endblock %}
</body>

templates/drive/drive_upload.html
{% load static %}

<html lang="en">
<head>
	<title>Drive Upload</title>
	<meta charset="UTF-8">
	<meta content="width=device-width, initial-scale=1" name="viewport">
	<!--===============================================================================================-->
	<link href="{% static 'signup/images/icons/favicon.ico' %}" rel="icon" type="image/png"/>
	<!--===============================================================================================-->
	<link href="v{% static 'signup/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/fonts/font-awesome-4.7.0/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/fonts/iconic/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
		  type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/vendor/animate/animate.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/vendor/animsition/css/animsition.min.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/vendor/select2/select2.min.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/vendor/daterangepicker/daterangepicker.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<link href="{% static 'signup/css/util.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'signup/css/main.css' %}" rel="stylesheet" type="text/css">
	<!--===============================================================================================-->
	<style>
   #datefield  *{
		 width: 200px;
	     height: 60px;
		 margin: 0 auto;


  height: 35px;
  margin: 0 auto;
  width: 100%;
  font-family: Poppins-Regular;
  font-size: 14px;

  text-transform: uppercase;
  /*background-color: #959595;*/
  outline: none;
  border: 0;
  border-radius: 3px;
  padding: 0 3px;
  /*color: #fff;*/
}
input[type=date]::-webkit-datetime-edit-month-field {attendance/
  color: red;
}
input[type=date]::-webkit-datetime-edit-day-field {
  color: white;
}
input[type=date]::-webkit-datetime-edit-year-field {
  color: blue;
}
input[type=date]::-webkit-clear-button {
  font-size: 18px;
  height: 30px;
  position: relative;
  right: 5px;
  margin-right: 4px;
}
input[type=date]::-webkit-inner-spin-button {
  height: 30px;
}
input[type=date]::-webkit-calendar-picker-indicator {
  font-size: 18px;
}
input[type=date]::-webkit-calendar-picker-indicator:hover {
  background-color: #959595;
  color: #e6e6e6;
  cursor: pointer;
}
input[type=date]::-webkit-calendar-picker-indicator:active {
  color: blue;
}
}
--------------------------------------------------------------------------------
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial;
  color: white;
}

.split {
  height: 100%;
  width: 50%;
  position: fixed;
  z-index: 1;
  top: 0;
  overflow-x: hidden;
  //padding-top: 20px;
}

.left {
  left: 0;
  /*background-color: #111;*/
}

.right {
  right: 0;
  /*background-color: black;*/
}

.centered {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

.centered img {
  width: 150px;
  border-radius: 50%;
}

/*label{
    padding: 10px;
    background: red;
    display: table;
    color: #fff;
     }
*/

input[type="file"] {
    display: none;
     padding: 20px 50px;
     line-height: 1.2;
}
/*-----------------------------------------For Rounds-----------------------------*/
.multiselect {
  width: 200px;
}

.selectBox {
  position: relative;
}

.selectBox select {
  width: 100%;
  font-weight: bold;
}

.overSelect {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}

#checkboxes {
  display: none;
  border: 1px #dadada solid;
}

#checkboxes label {
  display: block;
}

#checkboxes label:hover {
  background-color: #1e90ff;
}
/*---------------------------For Table---------------------------*/

/*td {
          border: 1px solid black;
          border-collapse: collapse;
}*/

	</style>
</head>
<body>
<div>
	{% block content %}

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'signup/images/bg-01.jpg' %});">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form action="{% url 'drive_upload' %}" class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						DRIVE UPLOAD
					</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate="Name is required">
						<span class="label-input100">Company-Name</span>
						<input class="input100" id="id_name" maxlength="20" name="name" placeholder="Type Company_Name"
							   required type="text">
						<span class="focus-input100" data-symbol="&#xf3e9;"></span>
					</div>


					<div data-validate="Date is required" id="datefield">
						<span class="label-input100">DATE</span>
						<input class="input100" id="id_date" name="drive_date" placeholder="Type Date" required
							   type="date">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Time is required">
						<span class="label-input100">Time</span>
						<input class="input100" id="id_time" name="drive_time" placeholder="Select Time" required
							   type="time">
						<span class="focus-input100" data-symbol="&#xf337;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Venue is required">
						<span class="label-input100">Venue</span>
						<input class="input100" id="id_venue" maxlength="100" name="place" placeholder="Type Venue"
							   required type="text">
						<span class="focus-input100" data-symbol="&#xf1a8;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Campus Type is required">
						<span class="label-input100">Round1</span>
						<input class="input100" id="id_round1" maxlength="100" name="round1"
							   required type="text" value="Aptitude Round">
						<span class="focus-input100" data-symbol="&#xf14b;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Campus Type is required">
						<span class="label-input100">Round2</span>
						<input class="input100" id="id_round2" maxlength="100" name="round2"
							   required type="text" value="Technical Round">
						<span class="focus-input100" data-symbol="&#xf14b;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Campus Type is required">
						<span class="label-input100">Round3</span>
						<input class="input100" id="id_round3" maxlength="100" name="round3"
							   required type="text" value="HR Round">
						<span class="focus-input100" data-symbol="&#xf14b;"></span>
					</div>

					<div class="wrap-input100" data-validate="Campus Type is required">
						<span class="label-input100">Other Rounds</span>
						<input class="input100" id="id_other" maxlength="100" name="other"
							   placeholder="Rounds name seperated with comma(,)" type="text">
						<span class="focus-input100" data-symbol="&#xf14b;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Percentage is required">
						<span class="label-input100">X<sup>th</sup> Percentage Required</span>
						<input class="input100" id="id_tenth" max="100" maxlength="5" name="tenth"
							   placeholder="Type your 10th percentage" required type="text">
						<span class="focus-input100" data-symbol="&#xf10c;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Percentage is required">
						<span class="label-input100">XII<sup>th</sup> /diploma Percentage Required</span>
						<input class="input100" id="id_diploma_12" max="100" maxlength="5" name="diploma_12"
							   placeholder="Type your 12th/Diploma percentage" required type="text">
						<span class="focus-input100" data-symbol="&#xf10c;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="College name is required">
						<span class="label-input100">Engineering Required</span>
						<input class="input100" id="id_engineering" maxlength="5" name="engineering"
							   placeholder="Type your Marks" required type="text">
						<span class="focus-input100" data-symbol="&#xf174;"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-23" data-validate="Branch Name is required">
						<span class="label-input100">Branch</span><br>
						<table>
						<tr>
							<td>Computer Engineering<input  id="id_computer" name="Computer" type="checkbox"></td>
							<td>IT Engineering<input  id="id_IT" name="IT" type="checkbox"></td>
						</tr>
						<tr>
							<td>E&TC Engineering<input  id="id_entc" name="ENTC" type="checkbox"></td>
							<td>Production Engineering<input  id="id_prod" name="PROD" type="checkbox"></td>
						</tr>
						<tr>
							<td>Instrumentation Engineering<input  id="id_instru" name="INSTRU" type="checkbox"></td>
							<td>Mechanical Engineering<input  id="id_mech" name="MECH" type="checkbox"></td>
						</tr>
						</table>
						<!--<input class="input100" id="id_branch" maxlength="50" name="branch" placeholder="Type Branch Names"
							   required type="text">
						<span class="focus-input100" data-symbol="&#xf18d;"></span>-->
					</div>

					<div class="wrap-input100 validate-input" data-validate="Package is required">
						<span class="label-input100">Base Package</span>
						<input class="input100" id="id_package" maxlength="10" name="package"
							   placeholder="Type your Base_Package in LPA" type="text">
						<span class="focus-input100" data-symbol="&#xf111;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Campus Type is required">
						<span class="label-input100">Campus-Type</span>
						<select id="id_campus" name="campus" required>
							<option value="On">On</option>
							<option value="Off">Off</option>
							<option value="Pool">Pool</option>
						</select>
						<span class="focus-input100"></span>
					</div>


					<div class="text-right p-t-8 p-b-31">
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit">
								Drive Upload
							</button>
						</div>
					</div>
				</form>
				{% if error %}
				{{ error }}
				{% endif %}
			</div>
		</div>
	</div>

	{% endblock %}


	<!--===============================================================================================-->
	<script src="{% static 'signup/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<!--===============================================================================================-->
	<script src="{% static 'signup/vendor/animsition/js/animsition.min.js' %}"></script>
	<!--===============================================================================================-->
	<script src="{% static 'signup/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'signup/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<!--===============================================================================================-->
	<script src="{% static 'signup/vendor/select2/select2.min.js' %}"></script>
	<!--===============================================================================================-->
	<script src="{% static 'signup/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'signup/vendor/daterangepicker/daterangepicker.js' %}"></script>
	<!--===============================================================================================-->
	<script src="{% static 'signup/vendor/countdowntime/countdowntime.js' %}"></script>
	<!--===============================================================================================-->
	<script src="{% static 'signup/js/main.js' %}"></script>
	<!--===============================================================================================-->
	<!-----------------------For Date Field------------------------------->
	<script type="text/javascript">
		var dtToday = new Date();
		var month = dtToday.getMonth() + 1;
		var mmonth = dtToday.getMonth() + 2;
		var day = dtToday.getDate();
		var year = dtToday.getFullYear();
		if(month < 10)
			month = '0' + month.toString();
		if(mmonth < 10)
			mmonth = '0' + mmonth.toString();
		if(day < 10)
			day = '0' + day.toString();
		var minDate= year + '-' + month + '-' + day;
		var maxDate= year + '-' + mmonth + '-' + day;
		var dateControl = document.querySelector('input[type="date"]');
		dateControl.value = minDate;
		dateControl.min = minDate;
		dateControl.max = maxDate;
	</script>
	<!--===============================================================================================-->

</div>


</body>
</html>

templates/drive/round_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Round Details</title>
</head>
<body>
{% block content%}

log in key : {{ login_key }}
{% endblock %}
</body>
</html>

templates/drive/total_graph.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'drive/graphs/result_total_analysis.png' %}" rel="stylesheet" type="image/png">
</head>
<body>

    {% block content %}

    <p align="center"><img src="{% static 'drive/graphs/result_total_analysis.png' %}"></p>
    <br>

{% endblock %}
</body>